import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AdSlot } from "@/components/AdSlot";
import { getGuide, guideArticles, relatedGuides } from "@/content/guides";
import { SITE_NAME, SITE_URL } from "@/lib/site";

export const dynamicParams = false;
export function generateStaticParams(){return guideArticles.map((article)=>({slug:article.slug}))}

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{
  const {slug}=await params;const article=getGuide(slug);if(!article)return{};
  return {title:article.title,description:article.description,alternates:{canonical:`/guide/${slug}`},openGraph:{type:"article",title:article.title,description:article.description,url:`${SITE_URL}/guide/${slug}`,publishedTime:article.publishedAt,modifiedTime:article.updatedAt},twitter:{card:"summary",title:article.title,description:article.description}};
}

export default async function GuideArticlePage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;const article=getGuide(slug);if(!article)notFound();const related=relatedGuides(article);
  const query=new URLSearchParams({shape:article.shape,color:article.color,pattern:article.pattern,length:article.shape==="almond"||article.shape==="coffin"?"long":"medium"});
  const articleJsonLd={"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.description,datePublished:article.publishedAt,dateModified:article.updatedAt,inLanguage:"ja",author:{"@type":"Organization",name:SITE_NAME},publisher:{"@type":"Organization",name:SITE_NAME},mainEntityOfPage:`${SITE_URL}/guide/${slug}`};
  const breadcrumbJsonLd={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"ホーム",item:SITE_URL},{"@type":"ListItem",position:2,name:"ネイルガイド",item:`${SITE_URL}/guide`},{"@type":"ListItem",position:3,name:article.title,item:`${SITE_URL}/guide/${slug}`}]};
  return <main className="article-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleJsonLd)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbJsonLd)}}/><nav className="breadcrumb" aria-label="パンくずリスト"><Link href="/">ホーム</Link><span><Link href="/guide">ガイド</Link></span><span>{article.title}</span></nav><div className="article-layout"><article><header className="article-header"><p className="eyebrow">{article.category}</p><h1>{article.title}</h1><p className="lead">{article.description}</p><div className="article-meta"><span>公開 {article.publishedAt}</span><span>更新 {article.updatedAt}</span></div></header><div className="article-body"><div className="article-summary"><strong>この記事の結論</strong><p>{article.focus}</p></div><h2>まず知っておきたい特徴</h2><p>{article.focus}</p><p>ネイルはカラー見本や一枚の写真だけで見ると、実際に五本の指へ並んだときの面積や明るさを想像しにくいものです。形と長さが変われば同じ色でも印象が変わり、自然光と室内光でも透明感やラメの強さは違って見えます。候補を一つに絞り込む前に、自分の手の写真で比較し、普段の服装やアクセサリーまで含めた全体のバランスを確認すると失敗を減らせます。</p><h2>選ぶときの3つのポイント</h2><h3>1. {article.tips[0]}</h3><p>最初にここを確認すると、見た目だけでなく日常で扱いやすい候補へ絞れます。写真では手全体が写るようにして、一本だけを拡大しすぎず、五本の並びと指の長さの見え方を見ましょう。</p><h3>2. {article.tips[1]}</h3><p>色や光は面積が大きくなるほど強く感じられます。小さなサンプルでちょうどよく見えた色でも、全指へ置くと濃く感じる場合があります。透明感、艶、先端の色幅を一段ずつ変えて比べるのがおすすめです。</p><h3>3. {article.tips[2]}</h3><p>ネイルは手を止めた写真だけでなく、スマートフォンを持つ、文字を打つ、バッグを開けるといった動作の中でも目に入ります。見た目と使いやすさの両方を確認しておくと、付けたあとに長さや形で困りにくくなります。</p><AdSlot label="記事内広告"/><h2>こんな人・場面に向いています</h2><p>{article.bestFor}</p><p>ただし「似合う」は固定された正解ではありません。肌の印象、指の形、年齢だけで決めつけず、その日に着たい服やなりたい雰囲気を優先して構いません。迷った場合は、まず短め・透け感あり・装飾少なめの候補を基準にし、そこから色の深さやアートの量を足していくと比較しやすくなります。</p><h2>選ぶときの注意点</h2><p>{article.caution}</p><p>試着画面の結果は仕上がりを検討するためのイメージです。実際の施術では自爪のカーブ、使用するジェルやポリッシュ、塗る回数、照明によって差が出ます。サロンへ行く場合は、試着画像と一緒に「仕事で使う」「この長さまで」「この色より少し透明に」など生活上の条件も伝えると相談しやすくなります。</p><h2>デザイン例</h2><ul>{article.examples.map((example)=><li key={example}><strong>{example}</strong> — 形と色の主役を一つに絞り、ほかの要素を引き算すると手全体になじみやすくなります。</li>)}</ul><div className="article-cta"><h2>自分の手で試してみる</h2><p>この記事のおすすめ形・色を試着画面にセットします。写真はブラウザ内で処理され、サーバーには保存されません。</p><Link className="button light" href={`/try-on?${query}`}>この条件でネイルを試す</Link></div><h2>よくある質問</h2><h3>初心者はどの長さから試せばよいですか？</h3><p>普段の自爪より少しだけ長い程度か、短めから始めると扱いやすさを確認できます。見た目をもっと変えたいと感じたら、試着画面でミディアム、ロングの順に伸ばして比べましょう。</p><h3>サロンでは何を見せれば伝わりますか？</h3><p>好きなデザイン画像を一枚だけ見せるより、試着した手全体の画像、希望する形、避けたい色、必要な長さを一緒に伝えると相談が具体的になります。素材や爪の状態によって再現できる範囲は施術者へ確認してください。</p></div></article><aside className="article-aside"><p className="eyebrow">RELATED</p><h2>あわせて読みたい</h2><div className="related-links">{related.map((item)=><Link key={item.slug} href={`/guide/${item.slug}`}>{item.title}</Link>)}</div><Link href="/diagnosis" className="button ghost">似合うネイルを診断</Link></aside></div></main>;
}
